### ISSUE TITLE
Text doesn't seem to render properly (display stays in double-lo-res) during chain reactions

### ISSUE THREAD

**Issue by bhtooefr** [jeremysrand/a2bejwld#1]
I noticed while playing that an end of level chain reaction resulted in the game attempting to render text onto the graphics area, rather than in the text area at the bottom of the screen. Also, I had Open Apple held down during it. (Edit: Open Apple state doesn't matter.)

Haven't done any actual debugging of that, though.

Using AppleWin 1.25.0.4, emulating an Enhanced //e, and if it matters, on Windows 10 Pro 1607 x64 (but I really doubt that'd influence it).

Edit 2: Here's a screenshot:

![Improper text rendering](http://bhtooefr.org/images/a2bejwld-chain-rxn-bug.png)

Looks like the text area is getting initialized, but a chain reaction causes it to use the wrong memory offset.

**Comment by jeremysrand** [comment]
I think this is a bug which I have fixed in the last couple of weeks.  I am getting close to shipping v1.2 with a fix for this (along with mouse support).  If you like, you can test this build:

https://dl.dropboxusercontent.com/u/24892980/a2bejwld.dsk

I will probably ship v1.2 within the next week or so.

> On Sep 10, 2016, at 11:56 AM, Eric Rucker notifications@github.com wrote:
> 
> I noticed while playing that an end of level chain reaction resulted in the game attempting to render text onto the graphics area, rather than in a text area at the bottom of the screen. Also, I had Open Apple held down during it.
> 
> Haven't done any actual debugging of that, though.
> 
> Using AppleWin 1.25.0.4, emulating an Enhanced //e, and if it matters, on Windows 10 Pro 1607 x64 (but I really doubt that'd influence it).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Jeremy Rand
jeremy@rand-family.com

**Comment by peterferrie** [comment]
It's here in dbllores.s (and still present in 2.1), 
    sta LOWSCR
[write to screen]
    sta HISCR
[write to screen]

That leaves HISCR active.  After printing the LF, the wrong VLINE value is used by the 80-column firmware, and printing resumes at line 2 instead of line 21, losing one line of text.
If you reverse the LOWSCR and HISCR, then it works properly.

**Comment by peterferrie** [comment]
Separate but perhaps related, the "completed level 2" and later texts are printed too far to the right.

**Comment by jeremysrand** [comment]
I think I have just fixed the issues you reported in my most recent push to GitHub.  This fix will be in the next release which will probably be called v2.2.  I will get a build of this to you also.  Thanks for the feedback.

**Comment by peterferrie** [comment]
Yes, all fixed.
